In [2]:
import pandas as pd

In [9]:
d =pd.read_csv(r"C:\Users\KOIN\Downloads\pornstars_0.csv")
d.head()

,Unnamed: 0,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,0,Lana Rhoades,https://www.pornhub.com/pornstar/lana-rhoades,2,407,1800000000,https://ei.phncdn.com/pics/users/318/887/681/a...,True,True,Lana Rhoades is a Virgo born in September of 1...,"['Bang Bros Network', 'Girlsway', 'Passion-HD']",{'Twitter': 'https://www.twitter.com/lanarhoad...,"{'Relationship status': 'Open', 'Interested in...",2.0,2.0,[2],2.0,1900000.0
1,1,Angela White,https://www.pornhub.com/pornstar/angela-white,3,851,1200000000,https://ei.phncdn.com/(m=eQJ6GCjadOf)(mh=cJBLt...,True,True,"Although she now resides in California, this b...","['Girlsway', 'Brazzers', 'Evil Angel']",{'Official Site': 'https://onlyfans.com/angela...,"{'Relationship status': 'Single', 'Interested ...",3.0,3.0,[3],4.0,902000.0
2,2,Eva Elfie,https://www.pornhub.com/pornstar/eva-elfie,4,193,1000000000,https://ei.phncdn.com/pics/users/683/394/291/a...,True,True,About Eva Elfie\r\n\r\n ...,"['Wow Girls', 'Ultra Films', 'Pornhub Models']",{'Official Site': 'https://onlyfans.com/evaelf...,"{'Relationship status': 'Single', 'Interested ...",4.0,4.0,[4],3.0,2200000.0
3,3,Abella Danger,https://www.pornhub.com/pornstar/abella-danger,5,1085,1900000000,https://ei.phncdn.com/pics/users/730/712/871/a...,True,True,"Danger might be her last name, but when it com...","['Bang Bros Network', 'Brazzers', 'Reality Kin...",NaN,"{'Relationship status': 'Single', 'Interested ...",5.0,5.0,[5],5.0,1300000.0
4,4,Alex Adams,https://www.pornhub.com/pornstar/alex-adams,7,416,2800000000,https://ei.phncdn.com/pics/users/372/679/361/a...,True,True,About Alex Adams\r\n\r\n ...,"['Hot Crazy Mess', 'Bratty Sis', 'Perv Mom']",{'Official Site': 'https://linktr.ee/AlexAdams...,"{'Relationship status': 'Single', 'Interested ...",8.0,7.0,[7],10.0,1100000.0

In [8]:
d

,Unnamed: 0,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,0,Lana Rhoades,https://www.pornhub.com/pornstar/lana-rhoades,2,407,1800000000,https://ei.phncdn.com/pics/users/318/887/681/a...,True,True,Lana Rhoades is a Virgo born in September of 1...,"['Bang Bros Network', 'Girlsway', 'Passion-HD']",{'Twitter': 'https://www.twitter.com/lanarhoad...,"{'Relationship status': 'Open', 'Interested in...",2.0,2.0,[2],2.0,1900000.0
1,1,Angela White,https://www.pornhub.com/pornstar/angela-white,3,851,1200000000,https://ei.phncdn.com/(m=eQJ6GCjadOf)(mh=cJBLt...,True,True,"Although she now resides in California, this b...","['Girlsway', 'Brazzers', 'Evil Angel']",{'Official Site': 'https://onlyfans.com/angela...,"{'Relationship status': 'Single', 'Interested ...",3.0,3.0,[3],4.0,902000.0
2,2,Eva Elfie,https://www.pornhub.com/pornstar/eva-elfie,4,193,1000000000,https://ei.phncdn.com/pics/users/683/394/291/a...,True,True,About Eva Elfie\r\n\r\n ...,"['Wow Girls', 'Ultra Films', 'Pornhub Models']",{'Official Site': 'https://onlyfans.com/evaelf...,"{'Relationship status': 'Single', 'Interested ...",4.0,4.0,[4],3.0,2200000.0
3,3,Abella Danger,https://www.pornhub.com/pornstar/abella-danger,5,1085,1900000000,https://ei.phncdn.com/pics/users/730/712/871/a...,True,True,"Danger might be her last name, but when it com...","['Bang Bros Network', 'Brazzers', 'Reality Kin...",NaN,"{'Relationship status': 'Single', 'Interested ...",5.0,5.0,[5],5.0,1300000.0
4,4,Alex Adams,https://www.pornhub.com/pornstar/alex-adams,7,416,2800000000,https://ei.phncdn.com/pics/users/372/679/361/a...,True,True,About Alex Adams\r\n\r\n ...,"['Hot Crazy Mess', 'Bratty Sis', 'Perv Mom']",{'Official Site': 'https://linktr.ee/AlexAdams...,"{'Relationship status': 'Single', 'Interested ...",8.0,7.0,[7],10.0,1100000.0
5,5,Riley Reid,https://www.pornhub.com/pornstar/riley-reid,8,829,1800000000,https://ei.phncdn.com/pics/users/181/451/091/a...,True,True,American pornstar Riley Reid was born in May o...,"['Bang Bros Network', 'Jules Jordan', 'Twistys']",{'Official Site': 'https://onlyfans.com/rileyr...,"{'Relationship status': 'Taken', 'Interested i...",7.0,8.0,[8],7.0,2000000.0
6,6,Mia Malkova,https://www.pornhub.com/pornstar/mia-malkova,9,586,866000000,https://ei.phncdn.com/(m=bLqDuhKlbyaT)(mh=CvCw...,True,True,Some girls are so damn hot that they can get y...,"['Bang Bros Network', 'Twistys', 'Brazzers']",{'Official Site': 'https://www.miamalkova.com'...,"{'Relationship status': 'Single', 'Interested ...",9.0,9.0,[9],9.0,1500000.0
7,7,Violet Myers,https://www.pornhub.com/pornstar/violet-myers,10,300,527000000,https://ei.phncdn.com/pics/users/700/361/351/a...,True,True,About Violet Myers\r\n\r\n ...,"['Bang Bros Network', 'Mia Khalifa', 'Jerkaoke']",{'Official Site': 'https://onlyfans.com/violet...,"{'Relationship status': 'Single', 'Interested ...",11.0,10.0,[10],8.0,538000.0
8,8,Johnny Sins,https://www.pornhub.com/pornstar/johnny-sins,11,1017,2500000000,https://ei.phncdn.com/(m=bLqDuhKlbyaT)(mh=Ou_3...,True,True,Some wise-ass once said: every worthy battle n...,"['Brazzers', 'Reality Kings', 'Vixen']",{'Twitter': 'http://www.twitter.com/JohnnySins...,"{'Relationship status': 'Open', 'Interested in...",12.0,11.0,[11],12.0,546000.0
9,9,Lexi Luna,https://www.pornhub.com/pornstar/lexi-luna,12,402,499000000,https://ei.phncdn.com/pics/users/312/403/491/a...,True,False,Hot brunette Lexi Luna is a former sex educato...,"['1111 Customs', 'Brazzers', 'Cam Soda']","{'Official Site': 'https://www.iWantLexi.com',...","{'Relationship status': 'Open', 'Interested in...",20.0,12.0,[12],15.0,427000.0
10,10,Emily Willis,https://www.pornhub.com/pornstar/emily-willis,13,571,906000000,https://ei.phncdn.com/(m=eQJ6GCjadOf)(mh=JJ7tX...,True,True,About Emily Willis\r\n\r\n ...,"['Evil Angel', 'Girlsway', 'Brazzers']",{'Twitter': 'https://www.twitter.com/emilywill...,"{'Relationship status': 'Single', 'Interested ...",13.0,13.0,[13],11.0,736000.0
11,11,Brandi Love,https://www.pornhub.com/pornstar/brandi-love,14,651,798000000,https://ei.phncdn.com/(m=bLqDuhKlbyaT)(mh=4iT1...,True,True,Brandi Love started her porno career at the ag...,"['Moms Teach Sex', 'Sweetheart Video', 'Brazze...","{'Official Site': 'https://onlybrandi.com', 'T...","{'Relationship status': 'Open', 'Interested in...",15.0,14.0,[14],16.0,918000.0
12,12,Lena Paul,https://www.pornhub.com/pornstar/lena-paul,15,777,794000000,https://ei.phncdn.com/pics/users/212/897/721/a...,True,False,Lena Paul is an amazing girl with an even more...,"['Lena Paul X', 'Girlsway', 'Bang Bros Network']",{'Twitter': 'https://www.twitter.com/Lenaisape...,"{'Relationship status': 'Open', 'Interested in...",14.0,15.0,[16],13.0,1000000.0
13,13,Autumn Falls,https://www.pornhub.com/pornstar/autumn-falls,16,230,702000000,https://ei.phncdn.com/(m=eQJ6GCjadOf)(mh=D4ihw...,True,True,About Autumn Falls\r\n\r\n ...,"['MOFOS', 'New Sensations', 'Jules Jordan']",{'Official Site': 'https://onlyfans.com/autumn...,"{'Relationship status': 'Taken', 'Pornstar Pro...",27.0,16.0,[15],18.0,566000.0
14,14,Natasha Nice,https://www.pornhub.com/pornstar/natasha-nice,17,1005,475000000,https://ei.phncdn.com/(m=eQJ6GCjadOf)(mh=chhlO...,True,False,There’s a lot that’s nice about the deliciousl...,"['PUBA', 'Adult Time', 'Smut Puppet']",{'Official Site': 'https://onlyfans.com/benice...,"{'Relationship status': 'Single', 'Interested ...",18.0,17.0,[17],17.0,419000.0
15,15,Cory Chase,https://www.pornhub.com/pornstar/cory-chase,18,785,951000000,https://ei.phncdn.com/pics/users/243/129/202/a...,True,True,"You can’t always judge a book by its cover, an...","['Taboo Heat', 'Reality Kings', 'Mommys Girl']","{'Official Site': 'https://www.tabooheat.com',...","{'Relationship status': 'Open', 'Interested in...",17.0,18.0,[18],14.0,932000.0
16,16,Jordi El Nino Polla,https://www.pornhub.com/pornstar/jordi-el-nino...,19,571,1100000000,https://ei.phncdn.com/pics/users/083/307/982/a...,True,True,Jordi El Nino Polla is a guy who has the luck ...,"['MOFOS', 'Brazzers', 'Reality Kings']",{'Official Site': 'https://www.instagram.com/j...,"{'Relationship status': 'Single', 'Interested ...",19.0,19.0,[19],23.0,400000.0
17,17,Lexi Lore,https://www.pornhub.com/pornstar/lexi-lore,20,382,474000000,https://ei.phncdn.com/(m=bLqDuhKlbyaT)(mh=UNCa...,True,False,About Lexi Lore\r\n\r\n ...,"['Love Lexi Lore', 'Step Siblings Caught', 'Az...",{'Twitter': 'https://www.twitter.com/LexiLore'...,"{'Relationship status': 'Single', 'Interested ...",21.0,20.0,[20],27.0,675000.0
18,18,Adriana Chechik,https://www.pornhub.com/pornstar/adriana-chechik,21,1038,1300000000,https://ei.phncdn.com/pics/users/427/889/762/a...,True,True,Theres nothing wrong with wanting a little att...,"['Girlsway', 'Evil Angel', 'Digital Playground']",{'Twitter': 'https://twitter.com/adrianachechi...,"{'Relationship status': 'Single', 'Interested ...",16.0,21.0,[22],21.0,897000.0
19,19,Rae Lil Black,https://www.pornhub.com/pornstar/rae-lil-black,22,213,587000000,https://ei.phncdn.com/pics/users/379/785/601/a...,True,False,NaN,"['Hentaied', 'Futanari', 'Parasited']",{'Twitter': 'https://www.twitter.com/Raelilbla...,"{'Relationship status': 'Single', 'Interested ...",24.0,22.0,[21],19.0,891000.0
20,20,Kendra Lust,https://www.pornhub.com/pornstar/kendra-lust,23,450,472000000,https://ei.phncdn.com/(m=eQJ6GCjadOf)(mh=fvaou...,True,False,Thank you for checking out my official PornHub...,"['Bang Bros Network', 'Arch Angel Video', 'Bra...","{'Official Site': 'https://kendralust.com/', '...","{'Relationship status': 'Taken', 'Interested i...",25.0,23.0,[23],29.0,635000.0
21,21,Anastasia Knight,https://www.pornhub.com/pornstar/anastasia-knight,24,137,294000000,https://ei.phncdn.com/(m=bLqDuhKlbyaT)(mh=h6nu...,True,False,Anastasia Knight is very happy filming in many...,"['Hussie Pass', 'MOFOS', 'Jays POV']",NaN,"{'Relationship status': 'Single', 'Interested ...",10.0,24.0,[24],127.0,325000.0
22,22,Skylar Vox,https://www.pornhub.com/pornstar/skylar-vox,25,280,489000000,https://ei.phncdn.com/(m=bLqDuhKlbyaT)(mh=vuMP...,True,True,About Skylar Vox\r\n\r\n ...,"['Filthy Kings', 'Bang Bros Network', 'My Life...",{'Twitter': 'https://www.twitter.com/onlyskyla...,"{'Relationship status': 'Single', 'Interested ...",28.0,25.0,[26],22.0,534000.0
23,23,Nicole Aniston,https://www.pornhub.com/pornstar/nicole-aniston,26,750,589000000,https://ei.phncdn.com/pics/users/535/186/092/a...,True,False,Nicole Aniston is a petite blonde California b...,"['PUBA', 'Bang Bros Network', 'Naughty America']",{'Twitter': 'https://www.twitter.com/xnicolean...,"{'Relationship status': 'Single', 'Interested ...",29.0,26.0,[25],26.0,913000.0
24,24,Sky Bri,https://www.pornhub.com/pornstar/sky-bri,27,46,174000000,https://ei.phncdn.com/pics/users/u/002/147/898...,True,True,About Sky Bri\r\n\r\n ...,"['Mr Lucky POV', 'Slayed']",{'Official Site': 'https://onlyfans.com/realsk...,"{'Relationship status': 'Single', 'Interested ...",35.0,27.0,[27],20.0,157000.0
25,25,Ava Addams,https://www.pornhub.com/pornstar/ava-addams,29,478,652000000,https://ei.phncdn.com/(m=eQJ6GCjadOf)(mh=C2JI5...,True,False,Ava Addams brings her triple D boobs to the ta...,"['Bang Bros Network', 'Brazzers', 'PUBA']","{'Official Site': 'https://MyAvaAddams.com', '...","{'Relationship status': 'Open', 'Interested in...",31.0,29.0,[30],28.0,614000.0
26,26,Dani Daniels,https://www.pornhub.com/pornstar/dani-daniels,30,1046,485000000,https://ei.phncdn.com/pics/users/375/516/231/a...,True,False,Dani Daniels is a true freak. This babe never ...,"['PUBA', 'Reality Kings', 'Brazzers']",{'Twitter': 'https://www.twitter.com/akadanida...,"{'Relationship status': 'Taken', 'Interested i...",30.0,30.0,[32],33.0,750000.0
27,27,Gabbie Carter,https://www.pornhub.com/pornstar/gabbie-carter,31,239,498000000,https://ei.phncdn.com/pics/users/u/001/868/228...,True,False,NaN,"['Cam Soda', 'Reality Kings', 'Deeper']",{'Twitter': 'https://www.twitter.com/Imawful69...,"{'Relationship status': 'Single', 'Interested ...",47.0,31.0,[28],37.0,470000.0
28,28,Sara Jay,https://www.pornhub.com/pornstar/sara-jay,33,927,287000000,https://ei.phncdn.com/pics/users/496/884/752/a...,True,False,"Lady Jay, Lady Jay, what can we say? We know y...","['Sara Jay', 'Bang Bros Network', 'Angelina Ca...",{'Amazon Wishlist': 'https://www.amazon.com/wi...,"{'Relationship status': 'Single', 'Interested ...",33.0,33.0,[34],36.0,473000.0
29,29,Cherie DeVille,https://www.pornhub.com/pornstar/cherie-deville,35,1114,690000000,https://ei.phncdn.com/pics/users/322/604/821/a...,True,True,"Cherie Deville is the type of MILF who, if she...","['PUBA', 'Brazzers', 'She Seduced Me']",{'Official Site': 'https://onlyfans.com/cherie...,"{'Relationship status': 'Taken', 'Interested i...",39.0,35.0,[35],35.0,373000.0
30,30,Lena The Plug,https://www.pornhub.com/pornstar/lena-the-plug,36,77,163000000,https://ei.phncdn.com/(m=bLqDuhKlbyaT)(mh=cpt5...,True,False,About Lena The Plug\r\n\r\n ...,"['Holly Randall', 'Naked News', 'Pornhub Origi...",{'Official Site': 'https://onlyfans.com/lenath...,"{'Relationship status': 'Single', 'Interested ...",23.0,36.0,[40],40.0,393000.0
31,31,Alexis Fawx,https://www.pornhub.com/pornstar/alexis-fawx,37,739,835000000,https://ei.phncdn.com/pics/users/209/919/621/a...,True,False,If youre a little cub of a pervert searching f...,"['Brazzers', 'Bang Bros Network', 'Reality Kin...","{'Twitter': 'https://twitter.com/alexisfawx', ...","{'Relationship status': 'Single', 'Interested ...",34.0,37.0,[36],32.0,376000.0
32,32,LaSirena69,https://www.pornhub.com/pornstar/lasirena69,38,238,418000000,https://ei.phncdn.com/pics/users/557/632/831/a...,True,False,NaN,"['Brazzers', 'Reality Kings', 'Brazzers Traile...",NaN,"{'Relationship status': 'Single', 'Interested ...",61.0,38.0,[38],61.0,417000.0
33,33,Savannah Bond,https://www.pornhub.com/pornstar/savannah-bond,39,225,395000000,https://ei.phncdn.com/(m=bLqDuhKlbyaT)(mh=dYUJ...,True,False,About Savannah Bond\r\n\r\n ...,"['Brazzers', 'Evil Angel', 'Jules Jordan']",{'Twitter': 'https://www.twitter.com/savannahb...,"{'Relationship status': 'Single', 'Interested ...",38.0,39.0,[39],41.0,226000.0
34,34,Mariana Martix,https://www.pornhub.com/pornstar/mariana-martix,40,96,283000000,https://ei.phncdn.com/(m=bLqDuhKlbyaT)(mh=xw8H...,True,False,About Mariana Martix\r\n\r\n ...,['Brad Montana'],{'Official Site': 'https://onlyfans.com/marian...,"{'Relationship status': 'Single', 'Interested ...",40.0,40.0,[37],63.0,195000.0
35,35,Elsa Jean,https://www.pornhub.com/pornstar/elsa-jean,41,804,646000000,https://ei.phncdn.com/pics/users/221/333/031/a...,True,True,"Looking at the tiny Elsa ‘Dream’ Jean, you’d b...","['PUBA', 'Bang Bros Network', 'Team Skeet']",{'Twitter': 'https://www.twitter.com/elsajeanx...,"{'Relationship status': 'Single', 'Interested ...",32.0,41.0,[41],30.0,936000.0
36,36,Molly Little,https://www.pornhub.com/pornstar/molly-little,42,120,129000000,https://ei.phncdn.com/(m=bLqDuhKlbyaT)(mh=12nv...,True,False,NaN,"['Step Siblings Caught', 'Bratty Sis', 'Cum Sw...",NaN,"{'Relationship status': 'Single', 'Pornstar Pr...",87.0,42.0,[44],104.0,74700.0
37,37,Gina Valentina,https://www.pornhub.com/pornstar/gina-valentina,43,663,790000000,https://ei.phncdn.com/pics/users/658/065/211/a...,True,False,Brazilian girls with plump asses and perky lit...,"['Scam Angels', 'LetsDoeIt', 'Reality Kings']",{'Official Site': 'https://onlyfans.com/gvalen...,"{'Relationship status': 'Single', 'Interested ...",54.0,43.0,[43],53.0,470000.0
38,38,Sara Blonde,https://www.pornhub.com/pornstar/sara-blonde,44,101,147000000,https://ei.phncdn.com/(m=bLqDuhKlbyaT)(mh=u1Dx...,True,False,About Sara Blonde\r\n\r\n ...,"['Sara Films', 'Inka Sex', 'MamacitaZ']",{'Official Site': 'https://onlyfans.com/sarabl...,"{'Relationship status': 'Open', 'Interested in...",44.0,44.0,[47],62.0,120000.0
39,39,Eliza Ibarra,https://www.pornhub.com/pornstar/eliza-ibarra,45,515,540000000,https://ei.phncdn.com/pics/users/u/001/425/551...,True,False,About Eliza Ibarra\r\n\r\n ...,"['Girlsway', 'Twistys', 'Adult Time']",{'Twitter': 'https://www.twitter.com/Eliza22ib...,"{'Relationship status': 'Single', 'Interested ...",41.0,45.0,[42],31.0,266000.0
40,40,LeoLulu,https://www.pornhub.com/pornstar/leolulu,46,190,964000000,https://ei.phncdn.com/pics/users/229/015/532/a...,True,True,About LeoLulu\r\n\r\n ...,"['True Amateurs', 'Pornhub Awards', 'Pornhub C...",{'Official Site': 'https://onlyfans.com/leolul...,"{'Relationship status': 'Taken', 'Interested i...",36.0,46.0,[45],39.0,1300000.0
41,41,Macy Meadows,https://www.pornhub.com/pornstar/macy-meadows,47,145,132000000,https://ei.phncdn.com/(m=bLqDuhKlbyaT)(mh=Fmku...,True,False,About Macy Meadows\r\n\r\n ...,"['Jerkmate', 'FAMILYxxx', 'Jays POV']",{'Twitter': 'https://www.twitter.com/macymeado...,"{'Relationship status': 'Single', 'Interested ...",57.0,47.0,[53],165.0,108000.0
42,42,Jessica Sodi,https://www.pornhub.com/pornstar/jessica-sodi,48,10,26300000,https://ei.phncdn.com/(m=bLqDuhKlbyaT)(mh=EfuP...,True,False,About Jessica Sodi\r\n\r\n ...,NaN,{'Official Site': 'https://onlyfans.com/jessic...,"{'Relationship status': 'Open', 'Interested in...",85.0,48.0,[52],183.0,35800.0
43,43,Blake Blossom,https://www.pornhub.com/pornstar/blake-blossom,49,383,408000000,https://ei.phncdn.com/(m=eQJ6GCjadOf)(mh=jmtKo...,True,False,About Blake Blossom\r\n\r\n ...,"['Bang Bros Network', 'See Him Fuck', 'Hussie ...",{'Twitter': 'https://www.twitter.com/BLKBLSSM'},"{'Relationship status': 'Single', 'City and Co...",45.0,49.0,[49],38.0,286000.0
44,44,Lisa Ann,https://www.pornhub.com/pornstar/lisa-ann,50,866,592000000,https://ei.phncdn.com/pics/users/253/308/782/a...,True,False,"When it comes to Queens of Porn, you cannot av...","['The Lisa Ann', 'Cruel Media TV', 'Bang Bros ...",NaN,"{'Relationship status': 'Single', 'Interested ...",42.0,50.0,[48],48.0,725000.0
45,45,Alexis Texas,https://www.pornhub.com/pornstar/alexis-texas,52,510,280000000,https://ei.phncdn.com/pics/users/901/676/131/a...,True,False,Alexis Texas is a classic Texas girl with an a...,"['Roman Video', 'Bang Bros Network', 'Cruel Me...",{'Twitter': 'https://www.twitter.com/Alexis_te...,"{'Relationship status': 'Single', 'Interested ...",43.0,52.0,[46],45.0,721000.0
46,46,Kourtney Love,https://www.pornhub.com/pornstar/kourtney-love,53,129,336000000,https://ei.phncdn.com/(m=bLqDuhKlbyaT)(mh=Kz4s...,True,False,About Kourtney Love\r\n\r\n ...,"['ExposedLatinas', 'VR Latina', 'Milky Peru']","{'Official Site': 'https://kourtneylove.com/',...","{'Relationship status': 'Single', 'Interested ...",48.0,53.0,[50],42.0,198000.0
47,47,Alina Angel,https://www.pornhub.com/pornstar/alina-angel,54,58,88500000,https://ei.phncdn.com/(m=eQJ6GCjadOf)(mh=xCYG6...,True,False,About Alina Angel\r\n\r\n ...,NaN,{'Official Site': 'https://Arabicalinaangel.co...,"{'Relationship status': 'Taken', 'Interested i...",53.0,54.0,[55],123.0,65300.0
48,48,Valentina Nappi,https://www.pornhub.com/pornstar/valentina-nappi,55,776,423000000,https://ei.phncdn.com/pics/users/003/208/152/a...,True,False,How do you know you’ve got something truly spe...,"['LetsDoeIt', 'Bang Bros Network', 'Black 4K']",{'Official Site': 'https://onlyfans.com/valena...,"{'Relationship status': 'Taken', 'Interested i...",46.0,55.0,[56],49.0,458000.0
49,49,Lauren Phillips,https://www.pornhub.com/pornstar/lauren-phillips,56,837,489000000,https://ei.phncdn.com/pics/users/063/782/471/a...,True,False,"If youre craving a smoldering redhead, youll b...","['MYLF', 'Adult Time', 'Mommys Girl']",{'Twitter': 'https://www.twitter.com/@laurenfi...,"{'Relationship status': 'Single', 'Interested ...",56.0,56.0,[57],51.0,377000.0
50,50,Crystal Lust,https://www.pornhub.com/model/crystal-lust,62,101,576000000,https://ei.phncdn.com/pics/users/795/830/241/a...,True,True,About Crystal Lust ...,NaN,{'Twitter': 'https://twitter.com/OnlyCrystalLu...,"{'Relationship status': 'Open', 'Interested in...",52.0,62.0,[63],55.0,698000.0
51,51,Sweetie Fox,https://www.pornhub.com/model/sweetie-fox,1,292,975000000,https://ei.phncdn.com/(m=eidYGCjadOf)(mh=jod5m...,True,True,About Sweetie Fox ...,NaN,{'Official Site': 'https://www.sweetiefox.com/...,"{'Relationship status': 'Open', 'Interested in...",1.0,1.0,[1],1.0,1600000.0
52,52,Candy Love,https://www.pornhub.com/model/candy-love,6,219,771000000,https://ei.phncdn.com/pics/users/723/631/591/a...,True,False,About Candy Love ...,NaN,{'Official Site': 'https://onlyfans.com/candy-...,"{'Relationship status': 'Open', 'Interested in...",6.0,6.0,[6],6.0,1000000.0
53,53,Serenity Cox,https://www.pornhub.com/model/serenity-cox,28,107,438000000,https://ei.phncdn.com/(m=bLazqgKlbyaT)(mh=DBru...,True,True,About Serenity Cox ...,NaN,{'Official Site': 'https://onlyfans.com/sereni...,"{'Relationship status': 'Open', 'Interested in...",26.0,28.0,[29],25.0,339000.0
54,54,Morgpie,https://www.pornhub.com/model/morgpie,32,255,447000000,https://ei.phncdn.com/pics/users/816/628/772/a...,True,True,About Morgpie ...,NaN,"{'Official Site': 'https://linktr.ee/Morgpie',...","{'Relationship status': 'Single', 'Interested ...",22.0,32.0,[33],24.0,863000.0
55,55,MewSlut,https://www.pornhub.com/users/mewslut,34,10,103000000,https://ei.phncdn.com/(m=bLazqgKlbyaT)(mh=7hnV...,True,False,NaN,NaN,{'https://onlyfans.com/mewslut': 'https://only...,NaN,58.0,51.0,[],72.0,283000.0
56,56,Daniela Antury,https://www.pornhub.com/model/daniela-antury,51,22,216000000,https://ei.phncdn.com/(m=bLazqgKlbyaT)(mh=zWhV...,True,False,About Daniela Antury ...,NaN,{'Official Site': 'https://onlyfans.com/daniel...,"{'Relationship status': 'Taken', 'Interested i...",NaN,NaN,[51],NaN,NaN

In [5]:
d =pd.read_csv(r"C://Users//KOIN//Downloads//abc.csv")

In [6]:
d

  student  language  science  maths  history
0   kumar        90       56     34       34
1   kevin        10       34     32       67
2   sammy        90       23     12       32
3  janice        20       67     90       45
4   peter        30       56     45       65
5    prem        90       45     45       34
6  carrol        50       90     45       23

In [13]:
d.head()

  student  language  science  maths  history
0   kumar        90       56     34       34
1   kevin        10       34     32       67
2   sammy        90       23     12       32
3  janice        20       67     90       45
4   peter        30       56     45       65

In [14]:
d.info

<bound method DataFrame.info of   student  language  science  maths  history
0   kumar        90       56     34       34
1   kevin        10       34     32       67
2   sammy        90       23     12       32
3  janice        20       67     90       45
4   peter        30       56     45       65
5    prem        90       45     45       34
6  carrol        50       90     45       23>

In [15]:
d.columns

Index(['student', 'language', 'science', 'maths', 'history'], dtype='object')

In [18]:
d.tail(5)

  student  language  science  maths  history
2   sammy        90       23     12       32
3  janice        20       67     90       45
4   peter        30       56     45       65
5    prem        90       45     45       34
6  carrol        50       90     45       23